"""add telegram user id to bookings

Revision ID: 7cded8fe8dda
Revises: ffe0d025dc31
Create Date: 2026-09-14 20:56:39.734930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cded8fe8dda'
down_revision: Union[str, Sequence[str], None] = 'ffe0d025dc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'bookings',
        sa.Column(
            'telegram_user_id',
            sa.BigInteger(),
            nullable=False,
            server_default='0',
        ),
    )

    op.create_index(
        op.f('ix_bookings_telegram_user_id'),
        'bookings',
        ['telegram_user_id'],
        unique=False,
    )

    op.alter_column(
        'bookings',
        'telegram_user_id',
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_telegram_user_id'), table_name='bookings')
    op.drop_column('bookings', 'telegram_user_id')
    # ### end Alembic commands ###
