"""add trainer image url

Revision ID: f5c3514764eb
Revises: 7cded8fe8dda
Create Date: 2026-09-16 13:57:41.127819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c3514764eb'
down_revision: Union[str, Sequence[str], None] = '7cded8fe8dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'trainers',
    sa.Column(
        'image_url',
        sa.String(length=500),
        nullable=False,
        server_default='https://placehold.co/400x400',
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'image_url')
    # ### end Alembic commands ###
